version: '3'

services:
  redis:
    image: sameersbn/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  
  gypscie_core_api:
    image: gypscie_core_api:latest
    command: uvicorn apy:app --host 0.0.0.0 --port 5057
    ports:
      - "5057:5057"
    depends_on:
      - redis
    links:
      - redis

  myproj_worker:
    image: gypscie_core_api:latest
    command: rq worker --url redis://redis:6379 my_queue
    depends_on:
      - redis
    links:
      - redis